package echoprint

import (
	"encoding/json"
	"io/ioutil"
)

type echoprintMeta struct {
	Version  float64 `json:"version"`
	Filename string  `json:"filename"`
}

// CodegenFp represents a parsed json fingerprint generated by codegen
type CodegenFp struct {
	Metadata echoprintMeta `json:"metadata"`
	Code     string        `json:"code"`
	TrackID  uint32        `json:"track_id"`
}

// ParseCodegenFile parses a json file generated by codegen and returns an
// array of CodegenFp stucts
func ParseCodegenFile(path string) ([]CodegenFp, error) {
	t := trackTime("ParseCodegenFile")
	defer t.finish(false)

	jsonData, err := ioutil.ReadFile(path)
	if err != nil {
		return nil, err
	}

	var fpList []CodegenFp
	err = json.Unmarshal(jsonData, &fpList)
	return fpList, err
}
